from snakemake.utils import validate

validate(config, schema="schemas/config.schema.yaml")


workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"
include: "rules/find.smk"
include: "rules/type.smk"
include: "rules/align.smk"
include: "rules/depth.smk"
include: "rules/variant.smk"
include: "rules/consensus.smk"
include: "rules/summary.smk"


rule all:
    input:
        "qc/fastp/fastp.stats.tsv",
        "qc/multiqc.html",
        expand("type/{sample}.type", sample=config["samples"]),
        expand("depth/{sample}.depth.tsv", sample=config["samples"]),
        expand("depth/{sample}.depth.png", sample=config["samples"]),
        expand("depth/{sample}.low_depth.bed", sample=config["samples"]),
        expand("variants/{sample}.tsv", sample=config["samples"]),
        expand("consensus/{sample}.consensus.fa", sample=config["samples"]),
        "summary/all.summary.tsv",
