from snakemake.utils import validate

validate(config, schema="../schemas/config.schema.yaml")


workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu; ")


include: "rules/common.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/multiqc.smk"


rule all:
    input:
        "qc/fastp/fastp.stats.tsv",
        "qc/multiqc.html",
