$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  conda:
    type: object
    properties:
      activate:
        type: string
      basic:
        type: string
    required:
      - activate
      - basic

  database:
    type: string

  samples:
    type: array
    items:
      type: string
    minItems: 1
    uniqueItems: true

  threads:
    type: object
    properties:
      high:
        type: integer
      low:
        type: integer
    required:
      - high
      - low

  workdir:
    type: string

required:
  - conda
  - database
  - samples
  - threads
  - workdir
